name: 'dummy-action'
description: 'Dummy GitHub Action'
author: 'Sergio Freire <@bitcoder>'
inputs: 
  name:
    description: 'User defined name'
    required: false 
branding:
  color: 'red' 
  icon: 'umbrella'
runs:
  using: 'docker'
  image: 'Dockerfile'
